name: Deploy via git-ftp

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install git-ftp
        run: sudo apt-get update && sudo apt-get install git-ftp

      - name: Deploy
        run: |
          git ftp push \
            --auto-init \
            --user "${{ secrets.FTP_USERNAME }}" \
            --passwd "${{ secrets.FTP_PASSWORD }}" \
            ftp://${{ secrets.FTP_SERVER }}/public_html/myproject/